<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEKRPvn7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEKRPvn7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEKRPvn7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEKRPvn7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEKRPvn7\App_KernelDevDebugContainer([
    'container.build_hash' => 'EKRPvn7',
    'container.build_id' => 'ebe80378',
    'container.build_time' => 1669731718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEKRPvn7');
