<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOTE2n5W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOTE2n5W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOTE2n5W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOTE2n5W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOTE2n5W\App_KernelDevDebugContainer([
    'container.build_hash' => 'OTE2n5W',
    'container.build_id' => '2c9d5086',
    'container.build_time' => 1669809461,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOTE2n5W');
